-- 코드를 입력하세요

SELECT FLAVOR FROM (
    SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
    UNION ALL
    SELECT FLAVOR, TOTAL_ORDER from JULY
) AS TB
group by FLAVOR
ORDER BY sum(TOTAL_ORDER) DESC LIMIT 3;