SELECT 
    MONTH(A.START_DATE) AS MONTH,
    A.CAR_ID,
    (
        SELECT COUNT(*)
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
        WHERE MONTH(A.START_DATE) = MONTH(B.START_DATE)
          AND YEAR(A.START_DATE) = YEAR(B.START_DATE)
          AND A.CAR_ID = B.CAR_ID
          AND B.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    ) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
WHERE A.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
  AND A.CAR_ID IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
      GROUP BY CAR_ID
      HAVING COUNT(*) >= 5
  )
GROUP BY MONTH(A.START_DATE), A.CAR_ID
ORDER BY MONTH(A.START_DATE), A.CAR_ID DESC;